name: Sync

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在本 github 仓库 Settings->Secrets 中配置 GITEE_RSA_PRIVATE_KEY
          # GITEE_RSA_PRIVATE_KEY 是个人 ssh 私钥，即 ssh-keygen -t rsa -C "xxx@xxxx.com" 生成的 ~/.ssh/id_rsa
          # 需要把 ssh-keygen -t rsa -C "xxx@xxxx.com" 生成的 ~/.ssh/id_rsa.pub 公钥配置到 gitee 个人头像->设置->安全设置->SSH公钥 中
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:usegalaxy-cn/website.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:usegalaxy-cn/website.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: shenweiyan
          # 注意在本 github 仓库 Settings->Secrets 中配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: usegalaxy-cn/website
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main  
